In [1]:
import torch

In [2]:
# Check gpu availability
# Check if CUDA is available and set the device accordingly
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(f"PyTorch is using the GPU. Device: {device}")
    # Get the name of the GPU
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
else:
    device = torch.device('cpu')
    print("PyTorch is using the CPU.")

# Example: Create a tensor on the selected device
my_tensor = torch.randn(3, 3).to(device)
print(f"Tensor created on: {my_tensor.device}")

PyTorch is using the GPU. Device: cuda
GPU Name: GeForce 840M
Tensor created on: cuda:0


In [3]:
torch.__version__

'2.7.0+cu118'

# Introudction to Tensors

Creating tensors

In [4]:
# scaler
scaler = torch.tensor(3)
scaler

tensor(3)

In [5]:
scaler.ndim

0

In [6]:
# vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
# matrix
MATRIX = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX[1]

tensor([4, 5, 6])

In [10]:
print(MATRIX.ndim)
MATRIX.shape


2


torch.Size([2, 3])

In [5]:
t = torch.tensor([[[2,3]]])
t.ndim

3

In [6]:
t.shape

torch.Size([1, 1, 2])

In [12]:
# Create a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1166, 0.7101, 0.2315, 0.0781],
        [0.4469, 0.1201, 0.6831, 0.8652],
        [0.0459, 0.2313, 0.3675, 0.3753]])

In [13]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (RGB)
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [12]:
torch.zeros_like(torch.arange(5,15,3))

tensor([0, 0, 0, 0])

In [15]:
float_16_tensor = torch.tensor([2.0,3], dtype =torch.float16, device = 'cpu', requires_grad=False)
float_16_tensor.dtype

torch.float16

In [16]:
float_16_tensor.device

device(type='cpu')

# Tensor Math

In [17]:
# Create a tensor and add 10 to it
tensor = torch.tensor([5,10,15])
tensor + 10

tensor([15, 20, 25])

In [18]:
tensor

tensor([ 5, 10, 15])

In [19]:
# Multiply by 10
tensor * 10

tensor([ 50, 100, 150])

In [20]:
# Divide by 10
tensor/10

tensor([0.5000, 1.0000, 1.5000])

In [21]:
# Sub by 10
tensor - 10

tensor([-5,  0,  5])

In [22]:
# Try out tensor's built in functions
torch.mul(tensor, 10)

tensor([ 50, 100, 150])

In [23]:
torch.add(tensor, 10)

tensor([15, 20, 25])

In [24]:
torch.matmul(tensor, torch.tensor([5,5,5]))

tensor(150)

In [17]:
MAT = torch.tensor(([1,2,3],[4,5,6],[7,8,9]))

In [14]:
MAT.shape, MAT.size, MAT.dtype, MAT.ndim, MAT.device, MAT.requires_grad

(torch.Size([3, 3]),
 <function Tensor.size>,
 torch.int64,
 2,
 device(type='cpu'),
 False)

In [27]:
MAT.T, MAT.shape

(tensor([[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]),
 torch.Size([3, 3]))

In [28]:
torch.cuda.is_available()

True

In [29]:
# count number of devices
torch.cuda.device_count()

1

In [30]:
# putting tensors and models on gpu
# create a tensor on cpu as it is by default
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [31]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [32]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [33]:
### Moving tensors back to cpu
tensor_on_cpu = tensor.to('cpu')
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [34]:
# if nump then can't back it to cpu
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [35]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3], dtype=int64)

In [21]:
torch.max(MAT), torch.min(MAT), torch.mean(MAT.type(torch.float32)), torch.sum(MAT)

(tensor(9), tensor(1), tensor(5.), tensor(45))

In [22]:
MAT.argmax(), MAT.argmax(dim=0), MAT.argmax(dim=1)

(tensor(8), tensor([2, 2, 2]), tensor([2, 2, 2]))

##### Reshaping, stacking, squeezing, unsqueezing

In [27]:
x = torch.arange(1, 10.)
x, x.dtype, x.device, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.float32,
 device(type='cpu'),
 torch.Size([9]))

In [28]:
# Add an extra dimension to x
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))