In [6]:
import torch

In [7]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [14]:
a =torch.tensor([[[1, 2], 
                  [4, 5]],
                    [[7, 8], 
                     [10, 11]]])

In [15]:
a.ndim

3

In [16]:
a.shape

torch.Size([2, 2, 2])

In [26]:
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6], [7, 8, 9]],
                        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

In [27]:
TENSOR.shape, TENSOR.ndim, TENSOR.size()

(torch.Size([3, 3, 3]), 3, torch.Size([3, 3, 3]))

In [20]:
TENSOR @ TENSOR

tensor([[[  30,   36,   42],
         [  66,   81,   96],
         [ 102,  126,  150]],

        [[ 435,  468,  501],
         [ 552,  594,  636],
         [ 669,  720,  771]],

        [[1326, 1386, 1446],
         [1524, 1593, 1662],
         [1722, 1800, 1878]]])

In [21]:
torch.arange(5,15,3)

tensor([ 5,  8, 11, 14])

In [25]:
torch.zeros_like(torch.tensor([1, 2, 3]))

tensor([0, 0, 0])

In [35]:
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [31]:
TENSOR * 10

tensor([[[ 10,  20,  30],
         [ 40,  50,  60],
         [ 70,  80,  90]],

        [[100, 110, 120],
         [130, 140, 150],
         [160, 170, 180]],

        [[190, 200, 210],
         [220, 230, 240],
         [250, 260, 270]]])

In [34]:
torch.mul(TENSOR, 10)

tensor([[[ 10,  20,  30],
         [ 40,  50,  60],
         [ 70,  80,  90]],

        [[100, 110, 120],
         [130, 140, 150],
         [160, 170, 180]],

        [[190, 200, 210],
         [220, 230, 240],
         [250, 260, 270]]])

In [36]:
%%time
TENSOR @ TENSOR

CPU times: total: 0 ns
Wall time: 1 ms


tensor([[[  30,   36,   42],
         [  66,   81,   96],
         [ 102,  126,  150]],

        [[ 435,  468,  501],
         [ 552,  594,  636],
         [ 669,  720,  771]],

        [[1326, 1386, 1446],
         [1524, 1593, 1662],
         [1722, 1800, 1878]]])

In [43]:
lst = TENSOR[0][0].tolist()
lst

[1, 2, 3]

In [ ]:
for i in TENSOR[0][0].tolist():
    print(i, end=" ")

1 2 3 

In [ ]:
lst = TENSOR.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

TypeError: object of type 'int' has no len()