In [4]:
import tensorflow as tf

In [ ]:
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

In [3]:
print(tf.config.list_physical_devices('GPU'))

[]


In [4]:
with tf.device('/GPU:0'):
    a = tf.random.normal([2,2 ])
    b = tf.matmul(a, a)
    print(b)

tf.Tensor(
[[-0.08959484 -0.04629072]
 [ 0.12666859 -0.18078004]], shape=(2, 2), dtype=float32)


In [7]:
from tensorflow.keras import Sequential
from tensorflow.keras import layers

In [50]:
# Create the model
model = Sequential(
    [   layers.Input(shape=(2,)),
        layers.Dense(1, activation='sigmoid'),
        tf.keras.layers.Lambda(lambda x: tf.cast(x >= 0.5, tf.float32))
    ]
)

In [51]:
# Compile
model.compile(
    loss='binary_crossentropy',
    optimizer = 'sgd',
    metrics=['accuracy']
)

In [13]:
# Data
import numpy as np
X = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])
y = np.array([[0], [0], [0], [1]])

In [14]:
# Train
model.fit(X, y, epochs=1000, shuffle=True)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 514ms/step - accuracy: 0.5000 - loss: 0.7872
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.5000 - loss: 0.7866
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5000 - loss: 0.7859
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5000 - loss: 0.7852
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.7846
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.5000 - loss: 0.7840
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.7833
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 0.7827
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.5000 - loss: 0.7820
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5000 - loss: 0.7814
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7808
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accu

In [59]:
# Predict
model.predict(np.array([[0,0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[0.]], dtype=float32)

In [60]:
model.predict(np.array([[1,1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[1.]], dtype=float32)

In [55]:
model.predict(np.array([[1,0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[0.]], dtype=float32)

In [56]:
model.predict(np.array([[0,1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[0.]], dtype=float32)

In [19]:
(w1, w2), (b) = model.get_weights()
w1 = w1[0]
w2 = w2[0]
b = b[0]
w1, w2, b

(np.float32(-0.26874405), np.float32(1.202502), np.float32(-1.2483678))

In [21]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [30]:
sigmoid(b)

np.float32(0.42564172)

In [31]:
sigmoid(w1 + w2 + b)

np.float32(0.60310936)

In [32]:
sigmoid(w1 + b)

np.float32(0.2998419)

In [33]:
sigmoid(w2 + b)

np.float32(0.72448784)

In [34]:
sigmoid(-1.5)

np.float64(0.18242552380635635)

In [35]:
sigmoid(1 + 1 - 1.5)

np.float64(0.6224593312018546)

In [21]:
w = model.get_weights()

In [35]:
w

[array([[-0.26874405],
        [ 1.202502  ]], dtype=float32),
 array([-1.2483678], dtype=float32)]

In [26]:
type(w)

list

In [27]:
len(w)

2

In [31]:
w[1]

array([-1.2483678], dtype=float32)

In [30]:
type(w[1])

numpy.ndarray

In [57]:
weight = np.array([[1],[1]])
bias = np.array([-1])


In [58]:
model.set_weights([weight, bias])